language: go
go:
  - 1.4
  - 1.5
before_install:
  - export COMPILER=clang++-3.6
  - export CXX=g++-4.8
  - export CC=gcc-4.8
  - go get github.com/mattn/gom
script:
  - GOM_INSTALL_FLAGS=-test make prepare && make test
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-3.6
      - libbz2-dev
      - libsnappy-dev
